### ISSUE TITLE
POC

### ISSUE THREAD

**Issue by useafterfree** [useafterfree/formant-take-home#1]
## Details
- uses turbopack / next.js and tailwind
- requires node `18.2.0` and `yarn >= 1.22.19`
- uses `Zod` model / types and  react-form-hook with zod to validate form input on UI and API

## To run:
```
git clone https://github.com/useafterfree/formant-take-home
cd formant-take-home
yarn install
yarn run dev
```

## Tasks DONE
- [x] The server should have one REST POST endpoint.  Imagine you are submitting some robot description info ( name, number of arms, description ) to create an entity.  
- [x] You should have a GET endpoint that returns a list of robots
- [x] No need to have a database to store server data, you can just use data structure in memory. 
UI".  See: MemoryStore: `pages/api/robots`
- [x] The frontend should show a form that submits data to the REST endpoint and the list of all robots beneath it after submitted.
- [x] Your react components should have their props specified as typescript interfaces and should largely be typed

- [x] Create some sort of abstraction that makes the data store easy to replace witha. different kind of backend
- [x] The form should be centered on the screen and styled with some CSS you write yourself to make it look nice in appearance
## TODO
- [ ]  Run the app in a Dockerfile (if you run out of time, feel free to skip this )
- [ ]  Show simple SQL migration scripts to create database tables go for it  (if you run out of time, feel free to skip this )
`MemoryStore` class uses the prisma interface, so it can easily be swapped out: https://www.prisma.io/docs/getting-started/quickstart#2-model-your-data-in-the-prisma-schema
